audio_gallery/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r"^admin/", include(admin.site.urls)),
    url(r"^", include("audio_profiling.urls", namespace="audio_profiling", app_name="audio_profiling")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

audio_profiling/urls.py
from django.conf.urls import url
from .views import AudioFileDetail, AudioPageListView, SetLanguage


urlpatterns = [
    url(r'^$', AudioPageListView.as_view(), name='audio_pages'),
    url(r'^audio_file/(?P<pk>\w+)$', AudioFileDetail.as_view(), name='audio_file_detail'),
    url(r'^language$', SetLanguage.as_view(), name='set_language')
]

audio_profiling/models.py
import os
import logging

from django.db import models, transaction
from django.conf import settings


logger = logging.getLogger(__name__)


class AudioFile(models.Model):
    title = models.CharField(max_length=100, unique=True)
    audio_file = models.FileField(upload_to='files/songs/%Y/%m/%d')

    waveform = models.FileField(upload_to='files/waveforms', blank=True, null=True, editable=False)
    mp3 = models.FileField(upload_to='files/songs/%Y/%m/%d', blank=True, null=True, editable=False)
    spectrogram = models.FileField(upload_to='files/spectrograms', blank=True, null=True, editable=False)
    spectrum = models.FileField(upload_to='files/spectrums', blank=True, null=True, editable=False)

    category = models.ForeignKey("Category", null=True)
    audio_page = models.ForeignKey("AudioPage", null=True)
    start_page = models.BooleanField(blank=True, default=False)  # TODO unique=True (only for true)

    # depending on the audio frequency matplotlib will generate different figures, with different margins
    TOP_IMG_MARGIN = models.IntegerField(blank=True, null=True, editable=False)
    BOTTOM_IMG_MARGIN = models.IntegerField(blank=True, null=True, editable=False)
    RIGHT_IMG_MARGIN = models.IntegerField(blank=True, null=True, editable=False)
    LEFT_IMG_MARGIN = models.IntegerField(blank=True, null=True, editable=False)

    def __str__(self):
        return self.title

    # TODO move those settings (*_upload_path) to settings.py
    # like this (settings.py): WAVEFORM_UPLOAD_PATH=os.path.join(settings.MEDIA_ROOT, "waveforms")
    @property
    def waveform_upload_path(self):
        return os.path.join(settings.MEDIA_ROOT, "waveforms")
    @property
    def spectrogram_upload_path(self):
        return os.path.join(settings.MEDIA_ROOT, "spectrograms")
    @property
    def spectrum_upload_path(self):
        return os.path.join(settings.MEDIA_ROOT, "spectrum")
    @property
    def audio_file_name(self)->str:
        '''
        file base name without extension
        '''
        return os.path.splitext(os.path.basename(self.audio_file.path))[0]

    def _get_spectrum_name(self) -> str:
        return self.audio_file_name + "_spectrum.json"
    def _get_waveform_name(self) -> str:
        return self.audio_file_name + "_waveform.json"
    def _get_spectrogram_name(self) -> str:
        return self.audio_file_name + "_spectrogram.png"
    def _get_mp3_name(self) -> str:
        return os.path.splitext(self.audio_file.name)[0] + ".mp3"

    @property
    def spectrogram_url(self):
        if self.spectrogram:
            return self.spectrogram.url
    @property
    def spectrum_url(self):
        if self.spectrum:
            return self.spectrum.url
    @property
    def mp3_url(self):
        if self.mp3:
            return self.mp3.url
    @property
    def waveform_url(self):
        if self.waveform:
            return self.waveform.url

    def clean_old_file(self):
        # TODO finish this
        pass

    def create_files(self) -> None:
        from .tasks import create_waveform, create_mp3, create_spectrogram, create_spectrum
        create_spectrogram.delay(self.pk)
        create_waveform.delay(self.pk)
        create_spectrum.delay(self.pk)
        create_mp3.delay(self.pk)

    def save(self, *args, **kwargs):
        file_changed = False
        if self.pk:
            old = AudioFile.objects.get(pk=self.pk)
            if self.audio_file != old.audio_file:
                logger.info("audio file has changed")
                file_changed = True
        elif self.audio_file:
            file_changed = True
        super().save(*args, **kwargs)
        if file_changed:
            # TODO self.clean_old_file()
            transaction.on_commit(self.create_files)


class AudioPage(models.Model):
    name = models.CharField(max_length=100)
    categories = models.ManyToManyField("Category", blank=True)
    photo = models.ImageField(upload_to='files/photos/%Y/%m/%d', null=True, blank=True)
    description = models.TextField(blank=True)
    page_number = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=100)
    parent_category = models.ForeignKey("self", null=True, blank=True)

    def __str__(self):
        if self.parent_category:
            return str(self.parent_category) + "->%s" % self.name
        else:
            return self.name

    class Meta:
        verbose_name_plural = "Categories"

audio_profiling/views.py
import logging
import typing
from collections import namedtuple

from django.shortcuts import redirect
import django
import django.utils.translation
from django.views.generic import View, ListView, DetailView
import modeltranslation

from . import models
from .models import AudioFile, AudioPage
from . import conf

logger = logging.getLogger(__name__)


class SetLanguage(View):
    """
    TODO I should have used:
     https://docs.djangoproject.com/en/1.10/topics/i18n/translation/#django.views.i18n.set_language
    instead of rolling my own SetLanguage view...
    """
    # TODO https://docs.djangoproject.com/en/1.8/topics/i18n/translation/#the-set-language-redirect-view
    def get(self, request):
        user_language = request.GET.get("language", "en")  # type: str
        django.utils.translation.activate(user_language)
        request.session[django.utils.translation.LANGUAGE_SESSION_KEY] = user_language
        referer = request.META.get("HTTP_REFERER")
        if referer and "audio_file" in referer:  # TODO remove hardcoded URL...
            return redirect(referer)
        return redirect(request.GET.get("link", "/"))


AudioPageCategories = namedtuple("AudioPageCategories", ["audio_page", "categories"])
CategoryAudioFileTuple = namedtuple("CategoryAudioFileTuple", ["category", "audio_file"])
CategorySubcategoriesTuple = namedtuple("CategorySubcategoriesTuple", ["category", "subcategories"])
class AudioListMixin:
    @staticmethod
    def sort_by_page_number(instruments: modeltranslation.manager.MultilingualQuerySet) -> typing.List[models.AudioPage]:
        return sorted(instruments, key=lambda obj:  obj.page_number if obj.page_number is not None else float("inf"))

    def get_context_data(self, context)->typing.Dict:
        # normally we would write AudioPage.objects.all().order_by((0 * django.db.models.F('page_number')).desc(), 'name')
        # but django-modeltranslation has a bug, long story short we cannot do order_by with any expression
        # there is a pending pull request:
        # https://github.com/deschler/django-modeltranslation/pull/398
        # until that gets merged, we will use the slower approach of using sort_by_page_number function
        audio_pages = AudioPage.objects.all().order_by("name")
        audio_pages = AudioListMixin.sort_by_page_number(audio_pages)

        audio_pages_categories = []  # type: typing.List[AudioPageCategories]
        for audio_page in audio_pages:
            categories = []  # type: typing.List[typing.Union[CategoryAudioFileTuple,CategorySubcategoriesTuple]]
            for category in audio_page.categories.all().order_by("name"):
                if not category.parent_category and AudioFile.objects.filter(audio_page=audio_page,
                                                                             category=category).count():
                    categories.append(
                        CategoryAudioFileTuple(category,
                                               AudioFile.objects.filter(audio_page=audio_page,
                                                                        category=category).first()
                                               ))
                else:
                    subcategories = []  # type: typing.List[CategoryAudioFileTuple]
                    for subcategory in category.category_set.all().order_by("name"):
                        if AudioFile.objects.filter(audio_page=audio_page, category=subcategory).count():
                            subcategories.append(
                                CategoryAudioFileTuple(subcategory,
                                                       AudioFile.objects.filter(audio_page=audio_page,
                                                                                category=subcategory).first()
                                                       ))
                    if subcategories:
                        categories.append((CategorySubcategoriesTuple(category, subcategories)))
            audio_pages_categories.append(AudioPageCategories(audio_page, categories))

        context["audio_pages_categories"] = audio_pages_categories
        return context


class AudioFileDetail(DetailView, AudioListMixin):
    model = AudioFile
    template_name = "audio_profiling/audiofile_detail.html"

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        AudioListMixin.get_context_data(self, context)
        context["SPECTRUM_FFT_SIZE"] = conf.SPECTRUM_FFT_SIZE
        context["SPECTROGRAM_WIDTH"] = conf.SPECTROGRAM_WIDTH
        context["SPECTROGRAM_HEIGHT"] = conf.SPECTROGRAM_HEIGHT
        return context


class AudioPageListView(ListView, AudioListMixin):
    model = AudioPage
    context_object_name = "audio_pages"
    template_name = "audio_profiling/base.html"

    def get_context_data(self, **kwargs):
        context = super(AudioPageListView, self).get_context_data(**kwargs)
        return AudioListMixin.get_context_data(self, context)

    def get(self, request, *args, **kwargs):
        start_page_music = AudioFile.objects.filter(start_page=True).first()
        if start_page_music:
            return redirect("audio_profiling:audio_file_detail", pk=start_page_music.pk)
        return super(AudioPageListView, self).get(request, *args, **kwargs)

audio_profiling/templates/audio_profiling/audiofile_detail.html
{% extends 'audio_profiling/base.html' %}
{% load i18n %}
{% block css_files %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'musicfile_details.css' %}">
{% endblock %}
{% block content %}


<div class="row">
    <div class="col-md-9 col-lg-9 col-xs-12 ">
        <div class="row">
            <div id="description" class="col-md-12">
                <section id="title">
                    <h2 class="page-header">{{object.audio_page.name}}</h2>
                    {% if object.audio_page.description%}
                    <h2 class="page-header">
                        {{object.audio_page.description|linebreaks}}
                    </h2>
                    {% endif %}
                </section>
            </div>
            {% if object.audio_page.photo %}
            <div class="row  visible-xs visible-sm hidden-md hidden-lg" style="margin-left: 0px;margin-right:0px;"> <!-- negative margins were stacking -->
                <div class="col-md-3 col-lg-3 col-xs-12 visible-xs visible-sm hidden-md hidden-lg " >
                    <img class='img-responsive' style="padding-bottom:5px; height: 200px !important;" id="violin-photo2" src="{{object.audio_page.photo.url}}" alt="creating spectogram, please refresh"  />
                </div>
            </div>
            {% endif %}
        </div>
        <div class="row"> <!--spectrum -->
            <div class="col-md-12 ">
                <div id="spectrum_chart">
                     <h4>{% trans "Instantaneous frequency spectrum of the sound (at the end-averaged)" %}</h4>
                    <canvas id="canvas" style="z-index:100" width="547" height="250px" style="display: block;  border:0px solid #000000;"></canvas>
                </div>
            </div>
        </div>
    </div>
    {% if object.audio_page.photo %}
    <div class="col-md-3 col-lg-3 col-xs-12 hidden-xs hidden-sm">
        <img class='img-responsive' style="padding-bottom:5px" id="violin-photo" src="{{object.audio_page.photo.url}}"/>
    </div>
    {% endif %}
</div>

<div class="row" >
    <div id="audio_player"></div>
</div>
<h4>{% trans "Changes of sound amplitude in time" %}</h4>
<div class="row" id="waveform-row">
    <div class="insideWrapper">
        <div id="waveform"></div>
        <canvas class="coveringCanvas" id="waveform-legend" style="z-index: 100;border-right-width: 0px;"></canvas>
    </div>

    <div id="waveform-timeline"></div>
</div>
<h4>{% trans "Aggregate image of frequency spectrum changes in time" %}</h4>
<div class="row">
    <div class="insideWrapper">
        <img src="{{object.spectrogram_url|default_if_none:""}}" class="coveredImage img-responsive" id="spectogram" alt="creating spectrogram, please refresh the page">
        <canvas class="coveringCanvas" id="spectogramTimeStamp"></canvas>
    </div>
</div>
{% endblock %}



{% block js_files %}
<script src="{% static 'node_modules/enquire.js/dist/enquire.js' %}"></script>
<script src="{% static 'node_modules/wavesurfer.js/dist/wavesurfer.min.js' %}"></script>
<script src="{% static 'node_modules/wavesurfer.js/dist/plugin/wavesurfer.timeline.min.js' %}"></script>
<script>
    var LEFT_IMG_MARGIN=parseFloat("{{object.LEFT_IMG_MARGIN}}");
    var RIGHT_IMG_MARGIN=parseFloat("{{object.RIGHT_IMG_MARGIN}}");
    var TOP_IMG_MARGIN=parseFloat("{{object.TOP_IMG_MARGIN}}");
    var BOTTOM_IMG_MARGIN=parseFloat("{{object.BOTTOM_IMG_MARGIN}}");

    var WAVEFORM_LINK="{{object.waveform_url|default_if_none:""}}";
    var SPECTRUM_LINK="{{object.spectrum_url|default_if_none:""}}";

    var WAV_AUDIO_LINK="{{object.audio_file.url}}";
    var MP3_AUDIO_LINK="{{object.mp3_url|default_if_none:""}}";

    var SPECTRUM_FFT_SIZE={{SPECTRUM_FFT_SIZE}};
    var SPECTROGRAM_IMAGE_WIDTH={{SPECTROGRAM_WIDTH}};
    var SPECTROGRAM_IMAGE_HEIGHT={{SPECTROGRAM_HEIGHT}};

</script>
<script src="{% static 'musicfile_details.js' %}"></script>
{% endblock %}

audio_profiling/templates/audio_profiling/base.html
<!DOCTYPE html>
<!-- some part of the template has been taken from/is based on https://github.com/almasaeed2010/AdminLTE/blob/master/starter.html
which is licensed under the MIT license.
In case you need to edit some HTML, you might want to take a look at the comments in the starter.html file.
-->
<html>
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Audio gallery</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="{% static 'node_modules/admin-lte/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'node_modules/admin-lte/dist/css/AdminLTE.min.css' %}">
    <link rel="stylesheet" href="{% static 'node_modules/admin-lte/dist/css/skins/skin-blue.min.css' %}">
    <link rel="stylesheet" href="{% static 'logo_settings.css' %}">
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block css_files %}
    {% endblock %}
    <script src="{% static 'logo_load_failure_fallback.js' %}"></script>
  </head>
  <body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
      <header class="main-header">
        <a href="/" class="logo">
          <span class="logo-mini"><b><img src="{% static 'logos/logo_small.jpg' %}" width="50px" height="50px" onerror="logo_load_failure()"></b></span>
          <span class="logo-lg"><b><img src="{% static 'logos/logo.jpg' %}" style="vertical-align: top;" alt="TM" onerror="logo_load_failure()"></b></span>
        </a>
        <nav class="navbar navbar-static-top" role="navigation">
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
          </a>
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              {% load i18n %}
              {% get_current_language as LANGUAGE_CODE %}
              {% get_available_languages as LANGUAGES %}
              {% for available_language in LANGUAGES %}
                <li>
                  <a href="{% url 'audio_profiling:set_language' %}?language={{ available_language.0 }}"> <span style="color: rgb(255,255,255); padding-right: 10px;">{% ifequal available_language.0 LANGUAGE_CODE %}<b>{{ available_language.0|upper }}</b> {% else %}{{ available_language.0|upper }}{% endifequal %}</span></a>
                </li>
              {% endfor %}
            </ul>
          </div>
        </nav>
      </header>
      <aside class="main-sidebar">
        <section class="sidebar">
          <ul class="sidebar-menu">
            {% for audio_page_categories in audio_pages_categories %}
              <li class="treeview {%if object.audio_page == audio_page_categories.audio_page %}active{% endif %} ">
                <a href="#"><i class="fa fa-link"></i> <span>{%if object.audio_page == audio_page_categories.audio_page %}<b>{% endif %}{{audio_page_categories.audio_page.name}}{%if object.audio_page == audio_page_categories.audio_page %}</b>{% endif %}</span> {% if audio_page_categories.categories %} <i class="fa fa-angle-left pull-right"></i> {% endif %}</a>
                {% if audio_page_categories.categories %}
                  <ul class="treeview-menu {%if object.audio_page == audio_page_categories.audio_page %}menu-open{% endif %}">
                      {% for category_tuple in audio_page_categories.categories %}
                          {% if not category_tuple.subcategories %}
                              <li {%if category_tuple.audio_file.pk == object.pk %}class="active"{%endif%}><a href="{% url 'audio_profiling:audio_file_detail' pk=category_tuple.audio_file.pk %}">{{category_tuple.category.name}}</a></li>
                          {% else %}
                            <li>
                              <a href="#">
{#                              TODO move the "active" and "menu-open" calculations to views, get rid of code duplication#}
                                  <li class="treeview {% for subcategory_tuple in category_tuple.subcategories %}
                          {%if subcategory_tuple.audio_file.pk == object.pk %}active{% endif %}{% endfor %}">
                                      <a href="#"> <span>{{category_tuple.category.name}}</span> <i class="fa fa-angle-left pull-right"></i></a>
                                      <ul class="treeview-menu {% for subcategory_tuple in category_tuple.subcategories %}
                          {%if subcategory_tuple.audio_file.pk == object.pk %}menu-open{% endif %}{% endfor %}">
                                        {% for subcategory_tuple in category_tuple.subcategories %}
                                          <li {%if subcategory_tuple.audio_file.pk == object.pk %}class="active"{%endif%}><a href="{% url 'audio_profiling:audio_file_detail' pk=subcategory_tuple.audio_file.pk %}">{{subcategory_tuple.category.name}}</a></li>
                                        {% endfor %}
                                      </ul>
                                  </li>
                              </a>
                            </li>
                          {% endif %}
                      {% endfor %}
                  </ul>
              {% endif %}
              </li>
            {% endfor %}
          </ul>
        </section>
      </aside>
      <div class="content-wrapper">
        <section class="content">
        {% block content %}
        {% endblock %}
        </section>
      </div>
    </div>
    <script src="{% static 'node_modules/admin-lte/plugins/jQuery/jquery-2.2.3.min.js' %}"></script>
    <script src="{% static 'node_modules/admin-lte/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'node_modules/admin-lte/dist/js/app.min.js' %}"></script>
    <script src="{% static 'node_modules/admin-lte/plugins/slimScroll/jquery.slimscroll.min.js'%}"></script>
    <script src="{% static 'node_modules/admin-lte/plugins/fastclick/fastclick.min.js'%}"></script>
    {% block js_files %}
    {% endblock %}
  </body>
</html>